### ISSUE TITLE
Segfault when running getErrorProfile

### ISSUE THREAD

**Issue by ghost** [jstjohn/SimSeq#5]
Hello,
I am very much interested in using your program in order to test my own genome rearrangement detection script.
However, when trying to construct the error profile file, I get a segmentation fault.
Command was:
./getErrorProfile -sam=./temp.sam -ref=$db/Arabidopsis_thaliana.fa -readLen=78 -phred33 > error_profile.S.txt

The SAM file was generated using bwa 0.6.1. First line, as example, is :
AZ_0000:3:30:7644:3044#0    81  chr1    5   37  76M =   4981    4900    AAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAATCTTTAAATCCTACATCCATG    hhchhhghfdhghhhhchhhhhhehhhhhhhhhhhhfhhghhhfhhhghghhhhhhhhhghhhghhhhhhhhhhhh    XT:A:U  NM:i:0  SM:i:37 AM:i:37 X0:i:1  X1:i:0  XM:i:0  XO:i:0  XG:i:0  MD:Z:76

 The fasta file is similar to your example file, except there are 79 chars on each line instead of 100 in your case. 

Any help would be greatly appreciated.
Thanks,

A./

**Comment by jstjohn** [comment]
Hmm... you aren't hard clipping the reads are you? I don't remember if I designed the program to work with variable length reads or not. Also that quality string looks like phred64 rather than 33, unless your quality scores are off the charts. Look for a read with an "N" in it, and see what the quality is under the "N". I then look at an ASCII table and see if it looks like -33 would make that score near 0 (usually 0 or 2) or if -64 would do that. Try with -phred64, and if that doesn't work, let me know and I'll look into this further.
-John

http://www.asciitable.com/

**Comment by ghost** [comment]
Hello, and thanks for your answer.
The reads are of constant length (76bp), and the quality is indeed phred64 (quality of N is B). However, when using -phred64 instead of -phred33, the program still segfaults after some time.

A./

**Comment by jstjohn** [comment]
Alright, do you have a fairly small example (maybe 100MB or less) where it still segfaults, that I could download and use to debug? 
Thanks,
John

**Comment by ghost** [comment]
Hello,
here is a link to download the sample file (http://www.4shared.com/file/uMJqfRlB/temp.html?). I work on the whole assembled TAIR genome sequence as a reference, but I guess you can just download the first chromosome here: ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes/TAIR10_chr1.fas , it should be enough.

**Comment by jstjohn** [comment]
Hey again,
Unfortunately I can't replicate your problem with this data. It works fine for me. Here is exactly what I did:
1. With the latest version pulled from github
   cd cUtils
   make
   mkdir temp
   cd temp
   mv ~/Downloads/temp.sam .
   wget ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes/TAIR10_chr1.fas
   #change the first line to ">chr1" so that it matches the name in the sam file, this gave me an error "Sequence name chr1 not found in reference" but not a seg fault
   ../getErrorProfile -ref=TAIR10_chr1.fas -readLen=76 -sam=temp.sam -phred64 > ep.txt

And that did it for me. What command line is giving you the error? If you do what I just did above exactly, do you still get a segfault?

Best,
John St. John

**Comment by ghost** [comment]
Hello,
I followed your steps exactly, and strangely, it worked. Now the command that I tried to use on the complete files also seems to run just fine. Wonder what it was.

Thanks a lot for helping me solve this issue.

A./
